use std::process::Command;
use std::sync::{Mutex, MutexGuard, OnceLock};

static TEST_LOCK: OnceLock<Mutex<()>> = OnceLock::new();

fn test_lock() -> MutexGuard<'static, ()> {
    TEST_LOCK
        .get_or_init(|| Mutex::new(()))
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
}

struct FileGuard {
    path: std::path::PathBuf,
    original: Option<Vec<u8>>,
}

impl FileGuard {
    fn new(path: impl Into<std::path::PathBuf>) -> Self {
        let path = path.into();
        let original = std::fs::read(&path).ok();
        Self { path, original }
    }
}

impl Drop for FileGuard {
    fn drop(&mut self) {
        if let Some(ref content) = self.original {
            let _ = std::fs::write(&self.path, content);
        } else if self.path.exists() {
            let _ = std::fs::remove_file(&self.path);
        }
    }
}

fn run(args: &[&str]) -> String {
    let output = Command::new(env!("CARGO_BIN_EXE_ctxt"))
        .args(args)
        .output()
        .expect("ctxt binary should run");
    assert!(output.status.success(), "command failed: {args:?}");
    String::from_utf8(output.stdout).expect("stdout should be UTF-8")
}

#[test]
fn help_mentions_safety_defaults() {
    let _guard = test_lock();
    let stdout = run(&["--help"]);
    assert!(stdout.contains("SAFETY DEFAULTS"));
    assert!(stdout.contains("network_default=deny"));
}

#[test]
fn doctor_is_local_and_deterministic() {
    let _guard = test_lock();
    let stdout = run(&["doctor"]);
    assert!(stdout.contains("status: ok"));
    assert!(stdout.contains("provider_default: dummy"));
}

#[test]
fn providers_include_dummy_and_ollama_variants() {
    let _guard = test_lock();
    let stdout = run(&["providers", "list"]);
    assert!(stdout.contains("dummy"));
    assert!(stdout.contains("ollama-local"));
    assert!(stdout.contains("ollama-cloud-direct"));
}

#[test]
fn ask_dummy_provider_succeeds() {
    let _guard = test_lock();
    let stdout = run(&["ask", "--provider", "dummy", "How do I test this repo?"]);
    assert!(stdout.contains("Response from dummy provider:"));
    assert!(stdout.contains("Mock LLM response from CompText Dummy Provider."));
    assert!(stdout.contains("Received prompt: \"How do I test this repo?\""));

    // Verify response file was written
    let response_path = std::path::Path::new(".comptext/model_response.latest.json");
    assert!(response_path.exists());
    let response_content = std::fs::read_to_string(response_path).unwrap();
    assert!(response_content.contains("\"provider\": \"dummy\""));
}

#[test]
fn ask_ollama_provider_respects_network_deny_policy() {
    let _guard = test_lock();
    let output = std::process::Command::new(env!("CARGO_BIN_EXE_ctxt"))
        .args(["ask", "--provider", "ollama-local", "hello"])
        .output()
        .expect("ctxt binary should run");

    assert!(
        !output.status.success(),
        "command should fail because network is denied by policy"
    );
    let stderr = String::from_utf8(output.stderr).expect("stderr should be UTF-8");
    let stderr_lower = stderr.to_ascii_lowercase();
    assert!(
        stderr_lower.contains("network access denied") && stderr_lower.contains("ollama-local"),
        "unexpected stderr from network-denied ollama run: {stderr}"
    );
}

#[test]
fn propose_dummy_provider_succeeds() {
    let _guard = test_lock();
    let latest_path = std::path::Path::new("proposals/proposal.latest.json");
    let _latest_guard = FileGuard::new(latest_path);
    let task = "Smoke temporary proposal";
    let slugified_path = std::path::Path::new("proposals/proposal_smoke_temporary_proposal.json");
    let _slugified_guard = FileGuard::new(slugified_path);
    if slugified_path.exists() {
        let _ = std::fs::remove_file(slugified_path);
    }

    let stdout = run(&["propose", "--provider", "dummy", task]);
    assert!(stdout.contains("Proposal generated successfully."));
    assert!(stdout.contains("Proposal file: proposals/proposal_smoke_temporary_proposal.json"));
    assert!(stdout.contains("Latest reference: proposals/proposal.latest.json"));

    assert!(slugified_path.exists());
    assert!(latest_path.exists());

    let proposal_content = std::fs::read_to_string(latest_path).unwrap();
    assert!(proposal_content.contains("\"task\": \"Smoke temporary proposal\""));
    assert!(proposal_content.contains("\"schema_version\": \"0.1\""));
    assert!(proposal_content.contains("Mock patch generated by dummy provider:"));
}

#[test]
fn apply_and_validate_succeeds() {
    let _guard = test_lock();
    let mock_file = std::path::Path::new("tests/mock_applied_patch.rs");
    let _mock_file_guard = FileGuard::new(mock_file);
    std::fs::write(mock_file, "// initial\n").unwrap();

    let mock_proposal = serde_json::json!({
        "schema_version": "0.1",
        "task": "Test apply",
        "rationale": "Verify apply and validate commands",
        "preconditions": [],
        "affected_files": ["tests/mock_applied_patch.rs"],
        "operations": [
            {
                "op": "patch",
                "path": "tests/mock_applied_patch.rs",
                "detail": "Mock test patch detail"
            }
        ],
        "validation_commands": ["cargo --version"],
        "rollback_strategy": "none",
        "risk_notes": "none"
    });

    let proposal_path = std::path::Path::new("proposals/proposal_test_apply.json");
    let _proposal_guard = FileGuard::new(proposal_path);
    std::fs::write(
        proposal_path,
        serde_json::to_string_pretty(&mock_proposal).unwrap(),
    )
    .unwrap();

    let stdout_apply = run(&["apply", "--yes", "proposals/proposal_test_apply.json"]);
    assert!(stdout_apply.contains("Applying Proposal:"));
    assert!(stdout_apply.contains("Proposal applied and validated successfully."));

    let modified_content = std::fs::read_to_string(mock_file).unwrap();
    assert!(modified_content.contains("// Mock patch applied:"));

    let stdout_validate = run(&["validate"]);
    assert!(stdout_validate.contains("Standard local validation commands:"));
    assert!(stdout_validate.contains("cargo test"));
}

#[test]
fn apply_rejects_disallowed_paths() {
    let _guard = test_lock();
    let mock_proposal = serde_json::json!({
        "schema_version": "0.1",
        "task": "Malicious task",
        "rationale": "Try to edit forbidden file",
        "preconditions": [],
        "affected_files": [".env"],
        "operations": [
            {
                "op": "patch",
                "path": ".env",
                "detail": "inject secret"
            }
        ],
        "validation_commands": [],
        "rollback_strategy": "none",
        "risk_notes": "high"
    });

    let path = std::path::Path::new("proposals/proposal_malicious.json");
    let _proposal_guard = FileGuard::new(path);
    std::fs::write(path, serde_json::to_string_pretty(&mock_proposal).unwrap()).unwrap();

    let output = std::process::Command::new(env!("CARGO_BIN_EXE_ctxt"))
        .args(["apply", "--yes", "proposals/proposal_malicious.json"])
        .output()
        .expect("ctxt binary should run");

    assert!(
        !output.status.success(),
        "should fail on security policy violation"
    );
    let stderr = String::from_utf8(output.stderr).expect("stderr should be UTF-8");
    assert!(stderr.contains("Security Policy Violation: Path '.env' is not an allowed write path."));
}
